#spring.application.name=FamilyMedTrack

#spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5700/familymeddb
    username: postgres
    password: postgres

  flyway:
    enabled: true
    baseline-on-migrate: true
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none




