version: "3"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5700:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: familymeddb

